package guru.sfg.beer.order.service.domain;

public enum BeerOrderEventEnum {
  VALIDATE_ORDER, APPROVE_VALIDATION, DENY_VALIDATION,
  ALLOCATE_ORDER, APPROVE_ALLOCATION, ALLOCATION_FAILED, ALLOCATION_NO_INVENTORY,
  PICK_UP_BEER
}
