package guru.sfg.beer.order.service.domain;

public enum BeerOrderEventEnum {
  START_VALIDATION, APPROVE_VALIDATION, DENY_VALIDATION,
  START_ALLOCATION, APPROVE_ALLOCATION, DENY_ALLOCATION, ALLOCATION_NO_INVENTORY,
  PICK_UP_BEER
}
