# REFACTOR
# - add docker-compose yaml override files for environments (local-debug, production...)
# - add init.sql file to initialize database (only in override)
# - add volumes?
services:

  # Messaging
  jms:
    image: apache/activemq-artemis
    environment:
      - ARTEMIS_USER=admin
      - ARTEMIS_PASSWORD=admin
    ports:
      - "8161:8161"
      - "61616:61616"

  # Logging
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  # Database
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: mysql ${MYSQL_HEALTHCHECK_DB} --user=${MYSQL_ROOT_USER} --password='${MYSQL_ROOT_PASSWORD}' --silent --execute "SELECT 1;"
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d:ro

  # Cloud
  service-registry:
    image: migmolrod/mssc-service-registry
    healthcheck:
      test: [ "CMD-SHELL", "curl -fs http://localhost:8761/actuator/health | grep 'UP' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 4
    ports:
      - "8761:8761"

  api-gateway:
    image: migmolrod/mssc-api-gateway
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
      - SPRING_PROFILES_ACTIVE=local-discovery
      - SPRING_ZIPKIN_BASEURL=${SPRING_ZIPKIN_BASEURL}
    healthcheck:
      test: [ "CMD-SHELL", "curl -fs http://localhost:9090/actuator/health | grep 'UP' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 4
    ports:
      - "9090:9090"
    depends_on:
      service-registry:
        condition: service_healthy
      config-server:
        condition: service_healthy
      beer:
        condition: service_healthy
      inventory:
        condition: service_healthy

  config-server:
    image: migmolrod/mssc-config-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
      - SPRING_PROFILES_ACTIVE=local-discovery
    healthcheck:
      test: [ "CMD-SHELL", "curl -fs http://localhost:9091/actuator/health | grep 'UP' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 4
    ports:
      - "9091:9091"
    depends_on:
      service-registry:
        condition: service_healthy

  # Microservices
  inventory:
    image: migmolrod/mssc-beer-inventory-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
      - SPRING_PROFILES_ACTIVE=local,local-discovery
      - SPRING_ZIPKIN_BASEURL=${SPRING_ZIPKIN_BASEURL}
      - SPRING_ARTEMIS_HOST=${SPRING_ARTEMIS_HOST}
      - SPRING_CLOUD_CONFIG_URI=${SPRING_CLOUD_CONFIG_URI}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL_INVENTORY}
    healthcheck:
      test: [ "CMD-SHELL", "curl -fs http://localhost:9033/actuator/health | grep 'UP' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 4
    ports:
      - "9033:9033"
    depends_on:
      mysql:
        condition: service_healthy
      jms:
        condition: service_started
      service-registry:
        condition: service_healthy
      config-server:
        condition: service_healthy

  beer:
    image: migmolrod/mssc-beer-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
      - SPRING_PROFILES_ACTIVE=local-discovery,local
      - SPRING_ZIPKIN_BASEURL=${SPRING_ZIPKIN_BASEURL}
      - SPRING_ARTEMIS_HOST=${SPRING_ARTEMIS_HOST}
      - SPRING_CLOUD_CONFIG_URI=${SPRING_CLOUD_CONFIG_URI}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL_BEER}
    healthcheck:
      test: [ "CMD-SHELL", "curl -fs http://localhost:9031/actuator/health | grep 'UP' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 4
    ports:
      - "9031:9031"
    depends_on:
      mysql:
        condition: service_healthy
      jms:
        condition: service_started
      service-registry:
        condition: service_healthy
      config-server:
        condition: service_healthy
      inventory:
        condition: service_healthy

  order:
    image: migmolrod/mssc-beer-order-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
      - SPRING_PROFILES_ACTIVE=local-discovery,local
      - SPRING_ZIPKIN_BASEURL=${SPRING_ZIPKIN_BASEURL}
      - SPRING_ARTEMIS_HOST=${SPRING_ARTEMIS_HOST}
      - SPRING_CLOUD_CONFIG_URI=${SPRING_CLOUD_CONFIG_URI}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL_ORDER}
    healthcheck:
      test: [ "CMD-SHELL", "curl -fs http://localhost:9032/actuator/health | grep 'UP' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 4
    ports:
      - "9032:9032"
    depends_on:
      mysql:
        condition: service_healthy
      jms:
        condition: service_started
      service-registry:
        condition: service_healthy
      config-server:
        condition: service_healthy
      beer:
        condition: service_healthy
      inventory:
        condition: service_healthy

volumes:
  mysql-data:
