logging:
  level:
    guru: debug
server:
  port: 9031
sfg:
  brewery:
    beer_inventory_service_host: http://localhost:9033
spring:
  application:
    name: beer-service
  artemis:
    password: admin
    user: admin
  cache:
    jcache:
      config: classpath:ehcache.xml
  datasource:
    url: jdbc:h2:mem:testdb
  sql:
    init:
      mode: embedded
