logging:
  level:
    guru: debug
server:
  port: 9033
spring:
  application:
    name: inventory-service
  artemis:
    password: admin
    user: admin
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
  sql:
    init:
      mode: embedded
  zipkin:
    enabled: false
